### ISSUE TITLE
Shiny app for already analyzed Seurat objects

### ISSUE THREAD

**Issue by elimereu** [EskelandLab/ShinyArchRUiO#5]
Dears developers, 

thanks a lot for providing this nice shiny app. It is something really useful. However, I recently discovered that and I have my scATAC-seq data already analyzed as a R object. I wonder if your app enable to directly upload a Seurat object.

**Comment by ankushs0128** [comment]
Hi Elimereu , 
Unfortunately , At the moment, ShinyArchR.UiO doesnot support Visualization from scATAC-seq Seurat object.

**Comment by elimereu** [comment]
Ok, thanks for the prompt response!

That’s a pity bc you are using Seurat inside, isn't?

**Comment by ankushs0128** [comment]
We are planning to include other objects in upcoming releases . Closing issue for now. 
Thanks

**Comment by ankushs0128** [comment]
hi @elimereu,  Ideally what plots would you like to visualize in ShinyArchR from Seuratobject? We may be able to put it up something supporting UMAPS and Coverage plots in the next few days. If that works for you?

**Comment by elimereu** [comment]
Hi Ankush, 

Thanks for following up with it. Yes, it would be great to explore UMAPs with the different metadata and coverage plots.

Keep me posted, 

Elisabetta

**Comment by ankushs0128** [comment]
Hi Elisabetta , 
@elimereu Please feel free to test the visualization on Seurat Objects
https://github.com/EskelandLab/ShinyMultiomeUiO.

best
Ankush

**Comment by ankushs0128** [comment]
Closing for now here , please open an issue on https://github.com/EskelandLab/ShinyMultiomeUiO

**Comment by elimereu** [comment]
Dear Ankush, 

Thanks a lot!!! 
I will test you ASAP and let you know in case of any issue. 

Best wishes, 

Elisabetta
