### ISSUE TITLE
 Could not find previously saved ArchRProject in the path specified!

### ISSUE THREAD

**Issue by susrinivasan** [EskelandLab/ShinyArchRUiO#6]
Hi, I am trying to deploy Shiny ArchR and I have a directory under /srv/shiny-server/ShinyArchRUiO where all the shiny files reside. However, my ArchR project resides in my home directory /home/susrinivasan/proj_ArchR and in   my global.R, I have
savedArchRProject <- loadArchRProject(path="/home/susrinivasan/proj_ArchR"). I get an initialization error saying 
Error in loadArchRProject(path = "/home/susrinivasan/proj_ArchR") : 
  Could not find previously saved ArchRProject in the path specified!

I am baffled as to why it says this even  when my project is there and the directory is readable. I am stuck and would appreciate any help.
I tried running R on the server and loading the ArchR project and it loads just fine and I could save it back. Why is the Shiny App not able to open it?

**Comment by susrinivasan** [comment]
Hi,

Thanks for your prompt response. My directory structure of ArchR project
viz. projBaTP_W8_traj is as follows.
***@***.*** ~]$ ls -l projBaTP_W8_traj/
total 798456
drwxr-xr-x 6 susrinivasan tnbc      4096 May 15 15:40
AMULET_multiplets_integrated
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:46 Annotations
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:39 ArrowFiles
-rw-r--r-- 1 susrinivasan tnbc 126518927 Jan  5 15:17 Background-Peaks.rds
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:46 chromVar_W8_zscores
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:46 chromVar_zscores
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:46 D3to5_ATAC
drwxr-xr-x 2 susrinivasan tnbc     12288 May 15 15:47 Embeddings
drwxr-xr-x 4 susrinivasan tnbc      4096 May 15 15:52 GroupCoverages
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:58 ImputeWeights
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:56 IterativeLSI
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:56 IterativeLSI2
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:56 LSI_ATAC
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:56 LSI_RNA
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:56 Monocole3
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:57 Peak2GeneLinks
drwxr-xr-x 4 susrinivasan tnbc      4096 May 15 15:57 PeakCalls
drwxr-xr-x 4 susrinivasan tnbc     20480 May 15 15:58 Plots
-rw-r--r-- 1 susrinivasan tnbc     23995 Jan  5 15:18
PlotsBa.adult-vs-Ba+Cycling+Ba.LP.d3to5-Down-Motifs-Enriched.csv
-rw-r--r-- 1 susrinivasan tnbc     24328 Jan  5 15:18
PlotsBa.adult-vs-Ba+Cycling+Ba.LP.d3to5-Up-Motifs-Enriched.csv
-rw-r--r-- 1 susrinivasan tnbc     24153 Jan  5 15:18
PlotsBa+Cycling+Ba.LP.d3to5-vs-Ba.adult-Down-Motifs-Enriched.csv
-rw-r--r-- 1 susrinivasan tnbc     23978 Jan  5 15:18
PlotsBa+Cycling+Ba.LP.d3to5-vs-Ba.adult-Up-Motifs-Enriched.csv
drwxr-xr-x 2 susrinivasan tnbc      4096 May 15 15:58 Plots_integrated
-rw-r--r-- 1 susrinivasan tnbc     23039 Jan  5 15:18
PlotsLP+ML+Cycling.LP.d3to5-vs-Ba+Cycling+Ba.LP.d3to5-Down-Motifs-Enriched.csv
-rw-r--r-- 1 susrinivasan tnbc     24420 Jan  5 15:18
PlotsLP+ML+Cycling.LP.d3to5-vs-Ba+Cycling+Ba.LP.d3to5-Up-Motifs-Enriched.csv
-rw-r--r-- 1 susrinivasan tnbc      1487 Jan 31 11:30
PlotsT1_posRegDown_Tfs.csv
-rw-r--r-- 1 susrinivasan tnbc       693 Jan 31 11:30
PlotsT1_posRegUp_Tfs.csv
-rw-r--r-- 1 susrinivasan tnbc      1487 Jan 31 11:40
PlotsT9_posRegDown_Tfs.csv
-rw-r--r-- 1 susrinivasan tnbc       693 Jan 31 11:40
PlotsT9_posRegUp_Tfs.csv
-rw-r--r-- 1 susrinivasan tnbc    736520 Jan  5 15:18
QCed_cells_snATAC_7097_1512_13012_4559_for-matching_snRNA.RData
-rw-r--r-- 1 susrinivasan tnbc 690091162 May 15 16:18 Save-ArchR-Project.rds
***@***.*** ~]$


I copied this entire directory projBaTP_W8_traj from my development server.
If I run ShinyArchRUiO via RStudio on my development server, it is running
fine.  My ShinyArchRUiO on the Shiny server resides in /srv/shiny-server is
in
[susrinivasan@***** ~]$ cd /srv/shiny-server/
[susrinivasan@***** shiny-server]$ cd ShinyArchRUiO/
[susrinivasan@***** ShinyArchRUiO]$ ls -l
total 4064
-rwxr-xr-x 1 susrinivasan tnbc     208 May 15 11:44 app.R
-rwxr-xr-x 1 susrinivasan tnbc     142 May 15 11:44 app.R~
drwxr-xr-x 2 susrinivasan tnbc    4096 May 15 11:44 ArchRAnalysis
drwxr-xr-x 2 susrinivasan tnbc   94208 May 15 11:44 ArchRLogs
-rwxr-xr-x 1 susrinivasan tnbc    8480 May 16 09:13 global.R
-rwxr-xr-x 1 susrinivasan tnbc    8488 May 15 16:35 global.R~
-rwxr-xr-x 1 susrinivasan tnbc   35129 May 15 11:44 LICENSE
-rwxr-xr-x 1 susrinivasan tnbc 3901651 May 15 11:44 Plot-Results-W8Subtrajectory.pdf
drwxr-xr-x 4 susrinivasan tnbc    4096 May 15 11:44 Plots
-rwxr-xr-x 1 susrinivasan tnbc   11108 May 15 11:44 README.md
-rw-r--r-- 1 susrinivasan sdsc       0 May 15 16:14 Rplots.pdf
-rwxr-xr-x 1 susrinivasan tnbc   42788 May 15 11:44 server.R
-rwxr-xr-x 1 susrinivasan tnbc    3251 May 15 11:44 sessionInfo_shiny_demo_instance.txt
-rwxr-xr-x 1 susrinivasan tnbc   22449 May 15 11:44 ui.R

My global.r looks like

#####################################################################

#                         Load Data

#####################################################################

##Load the Saved projects folders from ArchR analysis as saved in ArchR full manual using  saveArchRProject() function
#Load Saved-project folders path e.g 'Save-ArchRProject2'<- loadArchRProject("path/to/your/Save-ArchRProject2"). Save project also after trajectory analysis e.g as Save-ArchRProject5

#Please see ArchR  full manual for saveArchRProject() function or use the ArchR.RMD for your analysis provided with the source code which follows the steps illustrated in ArchR full manual. Save-ArchRProject5
#



savedArchRProject <- loadArchRProject(path="/home/susrinivasan/projBaTP_W8_traj")
 
Thank you for your help.

Sumana

**Comment by ankushs0128** [comment]
ShinyArchR requires the analysis to be saved exactly as shown in ArchR Manual. If its possible, Could you please provide the input data folders as suggested in ShinyArchR.UiO readme. 

Thanks

**Comment by ankushs0128** [comment]
Feel free to reopen issue, if needed more information
