### ISSUE TITLE
Github repository empty

### ISSUE THREAD

**Issue by emmawwinchester** [EskelandLab/ShinyArchRUiO#8]
Hello! I'm trying to install, and here's the command and issue I'm running into:
git clone https://github.com/EskelandLab/ShinyArchR.UiO.git
Cloning into 'ShinyArchR.UiO'...
Username for 'https://github.com': wentworth@uchc.edu
Password for 'https://wentworth@uchc.edu@github.com':
fatal: Authentication failed for 'https://github.com/EskelandLab/ShinyArchR.UiO.git/'
When I check the link, there's a 404 not found error.

**Comment by ankushs0128** [comment]
HI @emmawwinchester
This should work. The repository name is ShinyArchRUiO.  
git clone git@github.com:EskelandLab/ShinyArchRUiO.git
Please feel free to open the issue , if you still have trouble cloning the repo. 
Thanks, 
A

**Comment by emmawwinchester** [comment]
This is still kicking back an error. 

Cloning into 'ShinyArchRUiO'...
Warning: Permanently added 'github.com,140.82.114.3' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ankushs0128** [comment]
Hi @emmawwinchester 
Could you please try to download the zip file.  

It seems there is some permission or unmatching SSH key problem on your ssh client.  Ensure that the SSH key you are using is added to your GitHub account.
Here is the link to repository for downloading it 
https://github.com/EskelandLab/ShinyArchRUiO.git. 

Let me know if problem still persists? 

best
A
